Branch and buttons creation
Ucoll/fend-landingpage pull request #3
Opened 2022-02-05 20:19 UTC by keikeka

2022-02-06 20:48 UTC, OvidioSantoro requested changes
I commented a pair of things about your PR, they're easy to solve!

2022-02-06 20:48 UTC, OvidioSantoro commented on src/js/component/Buttons/Favorite/Favorite.jsx
> +    </div>
Only one of those will be rendered at any given time. Each one of these should be a different component: one for the empty star and another for the golden one. If we manage to use it as SVG we could use fill it with CSS, but for the moment, we need two different components.

2022-02-06 20:48 UTC, OvidioSantoro commented on src/js/component/Buttons/Favorite/Favorite.jsx
> +    </div>
Also, whenever is possible, let's try and avoid using inline style properties (e.g: `"height="52" width="auto"`). In this particular case, these buttons are embedded in the Coll, we have a global class for them, in order to control the size of all buttons easily: `className="button-coll"`

2022-02-06 20:48 UTC, OvidioSantoro commented on src/js/component/Buttons/UCollLogo/UCollLogo.jsx
> +       width="auto"/>
Again, let's try and use CSS for all styling.

2022-02-07 18:38 UTC, OvidioSantoro approved these changes

2022-02-07 18:54 UTC, AslanSN approved these changes
All seems fine, tested in my local computer all worked as it should!

2022-02-07 19:03 UTC, merged